# Generated by Django 2.1.2 on 2020-09-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sex',
            field=models.IntegerField(choices=[(1, '男性'), (2, '女性')], default=1, verbose_name='性別'),
        ),
    ]
