# Generated by Django 2.1.2 on 2020-09-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sample_10',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_8',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_9',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sex',
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_1',
            field=models.IntegerField(blank=True, choices=[(1, '醤油'), (2, '塩'), (3, '豚骨'), (4, 'みそ'), (5, '鶏白湯')], null=True, verbose_name='スープ味'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_2',
            field=models.IntegerField(blank=True, choices=[(1, 'つけ麺'), (2, '担々麺'), (3, '油そば')], null=True, verbose_name='ラーメン種類'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='こってりど評価'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='からさ評価'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='値段評価'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_6',
            field=models.IntegerField(blank=True, null=True, verbose_name='アクセル評価'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_7',
            field=models.DateTimeField(blank=True, null=True, verbose_name='サンプル項目8 日時'),
        ),
    ]
