# Generated by Django 2.1.2 on 2020-09-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200925_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='memo',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='コメント欄'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_7',
            field=models.DateTimeField(blank=True, null=True, verbose_name='日時'),
        ),
    ]
