# Generated by Django 2.1.2 on 2020-09-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200925_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='サンプル項目1_文字列'),
        ),
        migrations.AddField(
            model_name='item',
            name='name2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='サンプル項目2_文字列'),
        ),
    ]
