# Generated by Django 2.1.2 on 2020-09-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200927_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ラーメン店'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='場所'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_6',
            field=models.IntegerField(blank=True, null=True, verbose_name='アクセス評価'),
        ),
    ]
