# Generated by Django 2.1.2 on 2020-10-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200928_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sample_cost',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='値段'),
        ),
    ]
