# Generated by Django 2.1.2 on 2020-10-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201019_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sample_menhutosa',
            field=models.IntegerField(blank=True, choices=[(1, '醤油'), (2, '塩'), (3, '豚骨'), (4, 'みそ'), (5, '鶏白湯')], null=True, verbose_name='麺の太さ'),
        ),
    ]
