# Generated by Django 2.1.2 on 2020-10-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_item_sample_menhutosa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sample_menhutosa',
            field=models.IntegerField(blank=True, choices=[(1, '極細麺(1.1mm)'), (2, '細麺(1.15mm)'), (3, '中細麺(1.25mm)'), (4, '中太麺(1.4mm)'), (5, '太麺(1.7〜1.875mm)'), (6, '極太麺(2.2〜2.5mm)')], null=True, verbose_name='麺の太さ'),
        ),
    ]
