# Generated by Django 2.1.2 on 2020-10-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201022_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='メニュー名称'),
        ),
    ]
