# Generated by Django 2.1.2 on 2020-10-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_item_name1'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sample_url',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='ホームページ'),
        ),
    ]
