# Generated by Django 2.1.2 on 2020-10-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201022_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sample_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_7',
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_1',
            field=models.IntegerField(blank=True, choices=[(1, '醤油'), (2, '塩'), (3, '豚骨'), (4, 'みそ'), (5, '鶏白湯'), (6, 'つけ麺'), (7, '担々麺'), (8, '油そば')], null=True, verbose_name='ラーメン種類'),
        ),
    ]
