# Generated by Django 2.2.9 on 2020-11-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201112_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/image', verbose_name='添付画像'),
        ),
    ]
