# Generated by Django 2.2.9 on 2020-12-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20201117_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '検索', 'verbose_name_plural': '検索'},
        ),
    ]
